
const AddReviewConstants = {

    LOAD_HOTEL_BY_ID: 'LOAD_HOTEL_BY_ID',
    LOAD_HOTEL_SUCCESS: 'LOAD_HOTEL_SUCCESS',
    CHANGE_RATING: 'CHANGE_RATING',
    SUBMIT_REVIEW: 'SUBMIT_REVIEW',
    SUBMIT_REVIEW_SUCCESS: 'SUBMIT_REVIEW_SUCCESS'
};

export { AddReviewConstants}
