const AppConstants = {

    LOAD_LOCATIONS: 'LOAD_LOCATIONS',
    LOAD_LOCATIONS_SUCCESS: 'LOAD_LOCATIONS_SUCCESS',
    LOAD_USERS: 'LOAD_USERS',
    LOAD_USERS_SUCCESS: 'LOAD_USERS_SUCCESS',
    LOAD_HOTELS: 'LOAD_HOTELS',
    LOAD_HOTELS_SUCCESS: 'LOAD_HOTELS_SUCCESS',
    ADDED_USER: 'ADDED_USER',
    LOGGED_IN_USER: 'LOGGED_IN_USER',
    LOGOUT: 'LOGOUT',

    LOGIN_USER:'LOGIN_USER'
};

export { AppConstants}