const RegisterConstants = {

    // ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    // ADD_USER_FAILURE: 'ADD_USER_FAILURE',
    ADD_USERNAME: 'ADD_USERNAME',
    ADD_NAME: 'ADD_NAME',
    ADD_PASSWORD: 'ADD_PASSWORD',
    ADD_LOCATION: 'ADD_LOCATION',
    ADD_USER: 'ADD_USER',
    SETUP_INPUT: 'SETUP_INPUT',
    REGISTER_FAIL: 'REGISTER_FAIL',

};

export { RegisterConstants }
