const LoginConstants = {

    CHANGE_USERNAME: 'CHANGE_USERNAME',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

};

export { LoginConstants}