const ViewReviewsConstants = {

    SAVE_HOTEL: 'SAVE_HOTEL',
    LOAD_REVIEWS: 'LOAD_REVIEWS',
    LOAD_REVIEWS_SUCCESS: 'LOAD_REVIEWS_SUCCESS',
    FILTER_FLAG: 'FILTER_FLAG',
    FILTER_BY_DATE: 'FILTER_BY_DATE',
    FILTER_BY_TOPIC: 'FILTER_BY_TOPIC',
    CHANGE_THRESHOLD: 'CHANGE_THRESHOLD',
    SORT_BY_TOPIC: 'SORT_BY_TOPIC',
    FROM_NEWEST: 'FROM_NEWEST',
    FROM_OLDEST: 'FROM_OLDEST',
    BY_TOPIC: 'BY_TOPIC',

};

export {ViewReviewsConstants}
